apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: gitops-release
spec:
  entrypoint: git-clone
  arguments:
    parameters:
    - name: repoURL
      value: git@github.com:kszpakowski/gitops-workflows-demo.git
    - name: gitMail
      value: workflows@example.com
    - name: gitUsername
      value: release workflow
  templates:
    - name: workflow-steps
      steps:
      - - name: clone-repo
          template: git-clone
      # - - name: update-version
      #     template: update-version
      # - - name: commit-new-version
      #     template: commit-new-version
      # - - name: create-pull-request
      #     template: create-pull-request
      # - - name: send-notification
      #     template: send-notification
    - name: git-clone
      inputs:
        parameters: 
          - name: repoURL
          - name: gitMail
          - name: gitUsername
        artifacts:
        - name: config-repo
          path: /src
          git:
            repo: "{{inputs.parameters.repoURL}}"
            revision: "master"
            sshPrivateKeySecret:
              name: repo-creds
              key: ssh-private-key
      container:
        image: golang:1.10
        command: [sh, -c]
        args: 
          - >
              git config --global user.email "{{inputs.parameters.gitMail}}"
              && git config --global user.name "{{inputs.parameters.gitUsername}}" 
              && git checkout -b feature/update-version
              && echo "tag:v0.2.0" > values.yaml 
              && git add values.yaml 
              && git commit -m "values update"
              && ssh -o StrictHostKeyChecking=no argo-workflows@example.com uptime
              && git push --set-upstream origin feature/update-version
        workingDir: /src
    - name: update-version
      inputs:
        parameters:
          - name: msg
            value: "updating version"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]
    - name: commit-new-version
      inputs:
        parameters:
          - name: msg
            value: "commiting-new-version"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]
    - name: create-pull-request
      inputs:
        parameters:
          - name: msg
            value: "creating pull request"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]
    - name: send-notification
      inputs:
        parameters:
          - name: msg
            value: "sending notification"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]