apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: gitops-release
spec:
  templates:
    - name: hello-world
      inputs:
        parameters:
          - name: msg
            value: "hello world"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]