apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: gitops-release
spec:
  entrypoint: workflow-steps
  templates:
    - name: workflow-steps
      steps:
      - - name: clone-repo
          template: git-clone
      # - - name: update-version
      #     template: update-version
      # - - name: commit-new-version
      #     template: commit-new-version
      # - - name: create-pull-request
      #     template: create-pull-request
      # - - name: send-notification
      #     template: send-notification
    - name: git-clone
      inputs:
        artifacts:
        - name: config-repo
          path: /src
          git:
            repo: https://github.com/kszpakowski/gitops-workflows-demo.git
            revision: "master"
      container:
        image: golang:1.10
        command: [sh, -c]
        args: [ "git config --global user.email \"workflows@example.com\" && git config --global user.name \"release workflow\" && git status"]
        workingDir: /src
    - name: update-version
      inputs:
        parameters:
          - name: msg
            value: "updating version"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]
    - name: commit-new-version
      inputs:
        parameters:
          - name: msg
            value: "commiting-new-version"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]
    - name: create-pull-request
      inputs:
        parameters:
          - name: msg
            value: "creating pull request"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]
    - name: send-notification
      inputs:
        parameters:
          - name: msg
            value: "sending notification"
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.msg}}"]