apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argo-workflows-sso
  namespace: argocd
spec:
  encryptedData:
    client-id: AgCV9B+/9Mnjeh6EN84Al8cOQmQtL8pcZS69xadeKDoPuUZnB0widEg1+xPjr56WcAWJJyuOsLZko+BVo8h2ZTiasFYcRXO11cX2oNzvD0x+MKClDE4nLZIiKuRXd+9tw7pYuNTgTQfukjE5xQeigdTojHDwA2xvcN1U2zVIK+4v6fcXUwLX4+TXfJiHHeKxzTfHsQ3bCSDwYCMjf07JP4QSaRiJYZmCA1zTkJB5hKyoCdhZf97kIpS2VbkkaAK8F/1b4F9aBG9Hr39f16+9mty9Udj4s42MkirjRlP/p/4E82dKeAbO7RxnFxK0/ckb27okmC+qXYf/QLPMqITeBc/VSIYs6PVzX2+gYhT/ftJsID9xDQpDOL9x9eZA0QvCHhrO+Taj0Z5Q0XSCul2MmyZd0NodFGPeDyxd3ZIZSDwotuPICPFxRr49yOOncZd2nUfryaRSeiDUKEAyjGztYOee5RuSluJti7tWZHdM3qsCHA5kjfnquIbowLFGdqGBKbGNPkbMK/zZHLDkRfV87/fWz0v/dt2ZUwa2KzzQ3L/HnImTrvfT/sEFcTsyNbPcqbBwIA7J+K2u+JN6Aw2ncE4mdqxtLY0Qr89nh0f/ayZegJtC8B+LwDRudZN/xe8GOqXGvXQ55YeLDVT2A0M7R/D0UwXL8UKLTb8DOdbsMbdjuu9EcQZUhJ+Lpl/7giV+xzmWlsRjfSYQfR35/ja7s2e5xAw=
    client-secret: AgB8UxKHPhDF0+ZVKcx9D8oZROTjipdR4TrAsQh7TqDvwmMdnurQAtNCnyAAwo49v3N46MQ3fw+0SMPd5RwM1kx2HREqQNNacf0P0LRw9yitzpCAJbgICA3y2vJp/dfoAlegyF0WNnqbhp5NqpSJrhqu6Jek9qJguivA9L0zQxkn1cebhfuNkbMulV/zlEV+ErHieo8jZAj3IzKfioqxKHwvGlMF/vkLxZ6Sw/uGNj1tp3Mf6y4Mce0YEQZ96HXxLKLD34Fj60KA34EItFd2gmMCWH/mm+aWGP767KvcvXTobpMLGg5VavFxLntKHGHvjTq3/aSROQYso+hVmUMr2C58pVjx/kCKm5zNSwVSx997PYZyOUxaw2bakcqF+j9raxkaKG+QQqJbpDehoicuaTkcb7+g4XiWqlo1wDPSKlhxpjOiXqT6o9gH0dKbyQYpwEk1OaqmxlzYMKgcxrg2EZ+xSSNwvMsi7kS3J6YnD2ONktdgCshTM3nHrBtmdMDF0wzb0NhYVxxZ/i42YrWgzQIpmV/vl/b+37Qa3n/7aYqk+z1ddgH7G5yiyr9E4R0L/zRnxSdqv3EPySMZDFhDlTFQ/tDBcrS8OsZKlKyt5P0JRpDL68rBTdblm9vGo4A1J3fisM9qxMJ3RNDSMjq4CUMgvL/D3MPUR/Qeh3yeWUw2+WVFue+1CTL32QnYYQw3AniRVDfXolilKOVgkZmD3jDEUvtvNssejsL++TC3
  template:
    metadata:
      name: argo-workflows-sso
      namespace: argocd

