apiVersion: v1
kind: ConfigMap
metadata:
  name: ca
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIC5zCCAc+gAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
    cm5ldGVzMB4XDTIxMTAyOTExMTgxN1oXDTMxMTAyNzExMTgxN1owFTETMBEGA1UE
    AxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKTZ
    mvEbqmtVxdyyGowcswH3eREGgJyULDNZjErjkelO48Pzd9jNqEtyvygmbMPlygkM
    sjDBjpklAaDkyEDULsX3IZ5aLIE2iAvhZIbdnH7ZeEIxNnOcOzCEOeVZMbptf4Q+
    /Za6LUCD/POIz5TSis83CkT08WoNIplPOJ3P3mzBO06vHK27ebUGNvmSV8P9ynGk
    wf720uQwIhWCrxHxdhYjH0O7bqURzvU/G/QQB5FQt77gzJeuQw6SXpFm003bFzdo
    ljyzYGIMW/Tsq4kHwcHpNtdOBgz57eDOsq9ojkAuZPJW7eMVxNhGCm6YjuCaBdtc
    YrxQK8NpNG+EOGqSjE0CAwEAAaNCMEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB
    /wQFMAMBAf8wHQYDVR0OBBYEFHEIqfACdk9NS9rfVY5XAglISTZCMA0GCSqGSIb3
    DQEBCwUAA4IBAQCHhswPU8e3oVbYiw40MNBI0MNX6Qnput5r1L08J8YKHpcXGJ4x
    co7Z8KLW5kY3NsoTKo+Hnc94q4m/Hm35hZrujir3RC9IUh/XSTMlzx1pBbXURKbj
    9IS9AbFqW7F2R0MweRQgpMGVJ3IxgeSQhUIidpuDVjAfihKUlnxVzgz9ef3RhnAR
    H01g/igQSIP0VPQ7iX7f+6OLWdsUY0O4FWSUW87DizytjGLWZF57Ib79HcGgo5Sc
    h7yfWtiPJn7QpSG+R9+T8iHwlEybtqhxTfouP3qsLHU6tBeQERhIZXf8W8127/hE
    j7QYlmvvY+QycPQDYhOnKaUzRWUhwjNWrqSr
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIICzTCCAbWgAwIBAgIRAOtInH71CFrjoM5xuDAaS5EwDQYJKoZIhvcNAQELBQAw
    ADAeFw0yMTExMDEwODEwMjdaFw0yMjAxMzAwODEwMjdaMAAwggEiMA0GCSqGSIb3
    DQEBAQUAA4IBDwAwggEKAoIBAQDK0ZbdsjEIsrt7gnS2IVTMMzDhNjNWO39WK1P3
    lMXiubQOCvksI7wJOtFDnx+0U7ahnuQndOy9bOzWCULR99t9naHiWG28OZNTGSim
    5Qx8mtnNRMGDanz5d5SlQL7d3/urpGNG/js2qkHCemB+gxlKeYavw42jvlLZpy9B
    8O4v9bFA6/zDNWYkbAgOfMjvf0vX7h/zHxDd2gnxDyJoLDwW8BYHwSQIxRYr+KkA
    /pf00SxF9kqtKZDr+YLxQS3JJIF2RN/kL5p5YcpwGs3k3sWQbaOwwixCAmixwPHl
    F0Uyv0DgU4BdXJAI9tYtGMymu33qy0q4M2wMZPeAL8SRQZZJAgMBAAGjQjBAMA4G
    A1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMCAGA1UdEQEB/wQWMBSCEmFyZ29j
    ZC5leGFtcGxlLmNvbTANBgkqhkiG9w0BAQsFAAOCAQEAFplIAWj/2rCrmKKj+uI2
    +sjfy6AAOS7VM3VhVMBdNzwy6id6IltAblzYwQNqB0GNHbPO+e+LCzIjDGI0gNUv
    T+mgQ3Hlu22ZUeuC6n5vmeYHX1CwXiN/yQvcgSUoD7usAOb7AG9B1A/lF1waPws2
    YtLCI8f1NS+8cqLtSqeSjOHq1Hi2S23VTEfLiao0ghaJUlGMyp/N9aVRGlwva/K5
    3hNQ803E7Uot+J8F9+fErPX07AEQsfGyWUTIztK7n+Y//2JfVFGEBCMWh1AXduDS
    ul9BcDVlQnh20ziNVuwoH53wZ/x+fZV1TBS7WC3Cfpar6x4zjVTKaAvhf8HhUANm
    iA==
    -----END CERTIFICATE-----
