apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  destination:
    namespace: argo
    server: 'https://kubernetes.default.svc'
  source:
    path: argo-workflows/overlays
    repoURL: 'https://github.com/kszpakowski/kind-infra'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
