apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-workflow
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: workflows-demo
  project: default
  source:
    directory:
      recurse: true
    path: ./sample-workflow
    repoURL: https://github.com/kszpakowski/kind-infra.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
        - CreateNamespace=true