apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: sealed-secrets-controller
      containers:
      - args:
        - --update-status
        name: sealed-secrets-controller